server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

spring:
  cloud:
    config:
      server:
        git:
          uri: "D:/Projects/Anonymous-Surveys/survey-app/config-server"
          search-paths: "src/main/resources"